version: "3.6"

x-shared-environment: &shared-environment
  restart: unless-stopped
  networks:
    - handtalk_extraction_plugin_network

services:
  api:
    <<: *shared-environment
    image: node:22.12.0
    container_name: handtalk-extraction-plugin_api
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./api:/app
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - 3000:3000

  page:
    <<: *shared-environment
    image: node:22.12.0
    working_dir: /app
    container_name: handtalk-extraction-plugin_page
    command: ["sh", "-c", "npm install && npm run dev"]
    volumes:
      - ./page:/app/
    ports:
      - 5173:5173
    environment:
      - HOST=0.0.0.0

  plugin:
    <<: *shared-environment
    image: node:22.12.0
    container_name: handtalk-extraction-plugin_plugin
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./plugin:/app
    command: ["sh", "-c", "npm install && npm run build && npm run dev"]
    ports:
      - 3333:3333

networks:
  handtalk_extraction_plugin_network:
    external: true