version: "3.6"

x-shared-environment: &shared-environment
  restart: unless-stopped
  networks:
    - handtalk_extraction_plugin_network

services:
  api:
    <<: *shared-environment
    image: node:22.12.0
    container_name: api
    environment:
      NODE_ENV: development
      API_ENDPOINT: http://api:3000/collect
    working_dir: /app
    volumes:
      - ./api:/app
    command: ["sh", "-c", "npm install && npm run dev"]
    ports:
      - 3000:3000

  page:
    <<: *shared-environment
    image: node:22.12.0
    working_dir: /app
    container_name: page
    command: ["sh", "-c", "npm install && npm run dev"]
    volumes:
      - ./page:/app/
    ports:
      - 5173:5173
    environment:
      - HOST=0.0.0.0

  plugin:
    <<: *shared-environment
    image: node:22.12.0
    container_name: plugin
    environment:
      NODE_ENV: development
    working_dir: /app
    volumes:
      - ./plugin:/app
    command: ["sh", "-c", "npm install && npm run build && node server.mjs"]
    ports:
      - 4000:4000

networks:
  handtalk_extraction_plugin_network:
    external: true